language: node_js
node_js:
  - "4.2"

services:
  - mongodb

addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server

install:
 - npm install
 - npm install istanbul
 - npm install -g standard
 - npm install -g snazzy
 - npm install -g pm2
 - export COVERALLS_SERVICE_NAME=travis-ci

before_script:
 - make configure

# run tests + coverage
script:
  - make tests
  - make standard  # checks JS standard

# send coverage report to coveralls.io
after_success:
  - make coveralls

# email notifications
notifications:
    email: false
